name: Deploy Dummy API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, stg, production)"
        required: true
        default: "dev"

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment | default('dev') }}
    runs-on: ubuntu-latest

    env:
      STAGE: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Serverless Framework and Plugins
        run: npm install -g serverless@3 serverless-wsgi serverless-python-requirements

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Lambda functions
        run: sls deploy -s $STAGE

      - name: Show Deployed API Endpoint
        run: sls info --stage $STAGE --verbose
