name: Deploy Dummy API

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # Optional: allow manual trigger for any branch
    inputs: {}

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Serverless Framework and Plugins
        run: npm install -g serverless@3 serverless-wsgi serverless-python-requirements

      - name: Install NPM dependencies (if package.json exists)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json found. Skipping npm install."
          fi

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.PROD_AWS_ACCESS_KEY_ID }} --secret ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}

      - name: Deploy Lambda functions
        run: sls deploy -s production

      - name: Verify Deployed API Endpoint
        run: |
          echo "Fetching deployed API URL..."
          sls info --stage production --verbose > deploy_info.txt

          cat deploy_info.txt

          URL=$(grep -o 'https://[^ ]*/dev/hello' deploy_info.txt || true)

          if [ -z "$URL" ]; then
            echo "❌ Could not find API endpoint in deployment output!"
            exit 1
          fi

          echo "Testing endpoint: $URL"

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$URL")

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ API did not return 200 OK. Response code: $RESPONSE"
            exit 1
          else
            echo "✅ API returned 200 OK!"
          fi
