name: Deploy Python WSGI API

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, stg, production)"
        required: true
        default: "dev"

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    env:
      STAGE: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Node.js (for Serverless Framework)
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Serverless Framework and Plugins
        run: npm install -g serverless@3 serverless-wsgi serverless-python-requirements

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Deploy Flask WSGI App
        run: sls deploy -s $STAGE

      - name: Show deployed API endpoint
        run: sls info --stage $STAGE --verbose
